"""cpus table

Revision ID: 52eb047446e8
Revises: ddb627d7ceab
Create Date: 2023-05-19 20:52:17.814272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52eb047446e8'
down_revision = 'ddb627d7ceab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cpu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Number_of_Cores', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('Number_of_threads', sa.String(length=64), nullable=True))
        batch_op.drop_column('number_of_cores')
        batch_op.drop_column('number_of_threads')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cpu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number_of_threads', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('number_of_cores', sa.VARCHAR(length=64), nullable=True))
        batch_op.drop_column('Number_of_threads')
        batch_op.drop_column('Number_of_Cores')

    # ### end Alembic commands ###
